#########################################################################################################################################
#
#
#   Sponsor: https://serveur-minecraft-vote.fr/
#   Sponsor 2 : https://minecraft-inventory-builder.com/
#   5€ gift code on Minecraft Vote Server : ZVOTEPARTY (https://serveur-minecraft-vote.fr/utiliser/un/code/cadeau?code=ZVOTEPARTY)
#   
#   Documentation: https://groupez.dev/resources/zvoteparty.124/wiki
#   Discord: https://discord.groupez.dev/
# 
# 
# ███████╗██╗░░░██╗░█████╗░████████╗███████╗██████╗░░█████╗░██████╗░████████╗██╗░░░██╗
# ╚════██║██║░░░██║██╔══██╗╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝╚██╗░██╔╝
# ░░███╔═╝╚██╗░██╔╝██║░░██║░░░██║░░░█████╗░░██████╔╝███████║██████╔╝░░░██║░░░░╚████╔╝░
# ██╔══╝░░░╚████╔╝░██║░░██║░░░██║░░░██╔══╝░░██╔═══╝░██╔══██║██╔══██╗░░░██║░░░░░╚██╔╝░░
# ███████╗░░╚██╔╝░░╚█████╔╝░░░██║░░░███████╗██║░░░░░██║░░██║██║░░██║░░░██║░░░░░░██║░░░
# ╚══════╝░░░╚═╝░░░░╚════╝░░░░╚═╝░░░╚══════╝╚═╝░░░░░╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░░░░╚═╝░░░
#
#
#   Commands and permissions:
#   - /vote » Open vote invenroy - zvoteparty.vote
#   - /zvoteparty » Show needed votes for vote party (aliases: /vp, /voteparty) - zvoteparty.use
#   - /zvoteparty reload » Reload configuration - zvoteparty.reload
#   - /zvoteparty config » Open ingame configuration - zvoteparty.config
#   - /zvoteparty version » Show plugin version
#   - /zvoteparty help » Send commands description and syntax - zvoteparty.help
#   - /zvoteparty add » Add vote to player - zvoteparty.add
#   - /zvoteparty startparty » Force launch a Vote Party - zvoteparty.startparty
#   
#   Placeholders:
#   - %zvoteparty_votes_recorded% » Returns the current amount of votes in the Vote Party.   
#   - %zvoteparty_votes_required_party% » Returns the amount of votes left that are needed for a Vote Party to happen.
#   - %zvoteparty_votes_required_total% » Returns the total amount of votes needed for a Vote Party to happen.
#   - %zvoteparty_player_votes% » Returns the total amount of votes a player has.
#   - %zvoteparty_votes_progressbar% » Return a progress bar for the vote party
#   
#   
#########################################################################################################################################

# Rewards when a player goes to vote
rewards:
  # Reward configuration, each reward entry has a unique ID
  1:
    percent: 10
    needToBeOnline: false # Player does not need to be online to receive the reward
    commands:
      - "eco give %player% 100"
    broadcast:
      - "&f%player% &7just won &a$100"
  
  2:
    percent: 30
    needToBeOnline: true # Player must be online to receive the reward
    commands:
      - "give %player% minecraft:stone 10"
    broadcast:
      - "&f%player% &7just won &ax10 stone"

  3:
    percent: 30
    needToBeOnline: false # Player does not need to be online to receive the reward
    commands:
      - "eco give %player% 500"
    broadcast: [] # No broadcast message for this reward

  4:
    percent: 30
    needToBeOnline: true # Player must be online to receive the reward
    commands:
      - "cr give %player% diamond"
    broadcast:
      - "&7&m----------"
      - "&f%player% &7just won &ax1 diamond"
      - "&7&m----------"

party:
  # Configuration for party votes
  votes_needed: 50 # The number of votes required to trigger the party rewards
  
  # Commands executed when the required number of votes is reached for online players
  global_commands:
    - "eco give %player% 100"

  # Commands executed in the console when the required number of votes is reached
  commands:
    - "eco give * 0.0000000009"

  # Rewards configuration for the party votes
  rewards:
    1:
      percent: 50
      commands:
        - "give %player% minecraft:diamond 1"
        
    2:
      percent: 50
      commands:
        - "cr give %player% test"

# Database configuration
sql:
  user: "homestead"
  password: "secret"
  port: 3306
  host: "192.168.10.10"
  database: "zvoteparty"
